settings:
  username: "VeLLL3"
  commit_msg: "⚡ Update README with the recent activity"
  max_lines: 5
  readme_file: "./README.md"
  disabled_events:
    - "comments"
  url_text: "{REPO}{ID}"
  date:
    timezone: "GMT+07:00"
    text: "🕒 Last synced: {DATE}"
    format: "dddd, mmmm dS, yyyy, h:MM:ss TT"
  commit_name: "readme-bot"
  commit_email: "41898282+github-actions[bot]@users.noreply.github.com"

messages:
  push: "⬆️ Pushed some commits to {URL}"
  issue_opened: "❗️ Opened a new issue {URL}"
  issue_closed: "✔️ Closed out issue {URL}"
  pr_opened: "💪 Opened a pull request {URL}"
  pr_closed: "❌ Closed a pull request without merging {URL}"
  pr_merged: "🎉 Merged a pull request {URL}"
  create_repo: "📔 Started a brand new repository {URL}"
  fork_repo: "🔱 Forked {FORK} from {URL}"
  wiki_create: "📖 Added a new wiki page {URL}"
  added_member: "🤝 Joined as a collaborator on {URL}"
  changes_approved: "👍 Approved changes on {URL}"
  changes_requested: "🔴 Requested {AMOUNT} change(s) on {URL}"
  new_release: "✌️ Shipped a new release {URL}"
  new_star: "⭐ Starred {URL}"
