settings:
  username: "VeLLL3"
  commit_msg: ":zap: Update README with the recent activity"
  max_lines: 5
  readme_file: "./README.md"
  disabled_events:
    - "comments"
  url_text: "{REPO}{ID}"
  date:
    timezone: "GMT+07:00"
    text: "Last Updated: {DATE}"
    format: "dddd, mmmm dS, yyyy, h:MM:ss TT"
  commit_name: "readme-bot"
  commit_email: "41898282+github-actions[bot]@users.noreply.github.com"

messages:
  push: ":arrow_up: Pushed to {REPO}"
  issue_opened: "❗️ Opened issue {ID} in {REPO}"
  issue_closed: ":heavy_check_mark: Closed issue {ID} in {REPO}"
  pr_opened: ":muscle: Opened PR {ID} in {REPO}"
  pr_closed: ":x: Closed PR {ID} in {REPO}"
  pr_merged: ":tada: Merged PR {ID} in {REPO}"
  create_repo: ":notebook_with_decorative_cover: Created new repository {REPO}"
  fork_repo: ":trident: Forked {FORK} from {REPO}"
